gem 'rails', '~> 4.0.0.beta1'
gem 'activeresource', git: 'git://github.com/rails/activeresource.git', require: 'active_resource'
gem 'rails-observers', git: 'git://github.com/rails/rails-observers.git'
gem 'protected_attributes', git: 'git://github.com/rails/protected_attributes.git'
gem 'rack-cache', require: 'rack/cache'

group :active_record do
  platforms :jruby do
    case ENV['CI_DB_ADAPTER']
    when 'mysql'
      gem 'activerecord-jdbcmysql-adapter', '>= 1.2'
      gem 'jdbc-mysql', '>= 5.1'
    when 'postgresql'
      gem 'activerecord-jdbcpostgresql-adapter', '>= 1.2'
      gem 'jdbc-postgres', '>= 9.2'
    else
      gem 'activerecord-jdbcsqlite3-adapter', '>= 1.2'
      gem 'jdbc-sqlite3', '>= 3.7'
    end
  end

  platforms :ruby, :mswin, :mingw do
    case ENV['CI_DB_ADAPTER']
    when 'mysql'
      gem 'mysql', '~> 2.8.1'
    when 'postgresql'
      gem 'pg', '>= 0.14'
    else
      gem 'sqlite3', '>= 1.3'
    end
  end
end

# group :mongoid do
#   gem 'mongoid', '>= 3.0'
#   gem 'mongoid-paperclip', '>= 0.0.8', :require => 'mongoid_paperclip'
#   gem 'carrierwave-mongoid', '>= 0.4', :require => 'carrierwave/mongoid'
# end

gem 'carrierwave', '>= 0.8'
gem 'devise', git: 'git://github.com/plataformatec/devise.git', branch: 'rails4'
gem 'dragonfly', '>= 0.9'
gem 'mini_magick', '>= 3.4'
gem 'mlb', '>= 0.6'
gem 'paperclip', '>= 3.4'
gem 'rails_admin', :path => '../../'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 4.0.0.beta1'
  gem 'coffee-rails', '~> 4.0.0.beta1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'

  gem 'uglifier', '>= 1.3'
end
